// Declarative rule definitions from the Python audit reference. No executable rule code.
export const BUILTIN_YAML: Record<string, string> = {
  'APPROLE-001':
    'version: 1\nrule:\n  id: APPROLE-001\n  status: stable\n  enabled: true\n  severity: critical\n  finding_kind: security_issue\n  title: Privileged policy assigned to AppRole\n  description: The AppRole issues a policy classified as privileged.\n  remediation: Replace the assigned policy with least-privilege workload policies.\n  object_types: [approle]\n  detector: approle_privileged_policy\n  parameters:\n    severity_mapping: {root: critical, administrative: high}\n  documentation: [https://developer.hashicorp.com/vault/api-docs/auth/approle]\n',
  'APPROLE-002':
    'version: 1\nrule:\n  id: APPROLE-002\n  status: review\n  enabled: true\n  severity: medium\n  finding_kind: risky_configuration\n  title: Broad SecretID reuse\n  description: A SecretID has unlimited uses or exceeds the configured reuse threshold.\n  remediation: Configure a finite secret_id_num_uses suitable for credential delivery.\n  object_types: [approle]\n  detector: approle_secret_id_uses\n  parameters:\n    field: secret_id_num_uses\n    zero_means: unlimited\n  documentation: [https://developer.hashicorp.com/vault/api-docs/auth/approle]\n',
  'APPROLE-003':
    'version: 1\nrule:\n  id: APPROLE-003\n  status: review\n  enabled: true\n  severity: high\n  finding_kind: risky_configuration\n  title: Long-lived or non-expiring SecretID\n  description: Generated SecretIDs do not expire or exceed the configured lifetime threshold.\n  remediation: Configure a finite secret_id_ttl suitable for the workload.\n  object_types: [approle]\n  detector: approle_secret_id_ttl\n  parameters:\n    field: secret_id_ttl\n    zero_means: non_expiring\n  documentation: [https://developer.hashicorp.com/vault/api-docs/auth/approle]\n',
  'APPROLE-004':
    'version: 1\nrule:\n  id: APPROLE-004\n  status: review\n  enabled: true\n  severity: info\n  finding_kind: review_recommendation\n  title: SecretID binding disabled\n  description: The role authenticates without a SecretID; safety depends on other constraints and deployment model.\n  remediation: Verify a strong alternative constraint such as narrow source CIDRs.\n  object_types: [approle]\n  detector: approle_secret_id_binding\n  parameters:\n    field: bind_secret_id\n    alternative_constraint: secret_id_bound_cidrs\n  documentation: [https://developer.hashicorp.com/vault/api-docs/auth/approle]\n',
  'APPROLE-005':
    'version: 1\nrule:\n  id: APPROLE-005\n  status: review\n  enabled: true\n  severity: medium\n  finding_kind: risky_configuration\n  title: Long-lived AppRole token\n  description: The role token TTL exceeds the configured review threshold.\n  remediation: Reduce token_ttl/token_max_ttl or document the exception.\n  object_types: [approle]\n  detector: approle_token_ttl\n  parameters:\n    fields: [token_ttl, token_max_ttl]\n  documentation: [https://developer.hashicorp.com/vault/api-docs/auth/approle]\n',
  'APPROLE-006':
    'version: 1\nrule:\n  id: APPROLE-006\n  status: review\n  enabled: true\n  severity: medium\n  finding_kind: risky_configuration\n  title: Periodic AppRole token\n  description: Periodic tokens can remain valid while renewed unless an explicit maximum TTL limits them.\n  remediation: Remove token_period or configure and monitor a hard lifetime cap.\n  object_types: [approle]\n  detector: approle_periodic_token\n  parameters:\n    period_field: token_period\n    hard_limit_field: token_explicit_max_ttl\n  documentation: [https://developer.hashicorp.com/vault/docs/concepts/tokens]\n',
  'APPROLE-007':
    'version: 1\nrule:\n  id: APPROLE-007\n  status: review\n  enabled: true\n  severity: low\n  finding_kind: review_recommendation\n  title: Privileged role without token CIDR binding\n  description: A sensitive role has no token source-network restriction.\n  remediation: Consider token_bound_cidrs when stable workload networks make it practical.\n  object_types: [approle]\n  detector: approle_cidr_review\n  parameters:\n    field: token_bound_cidrs\n  documentation: [https://developer.hashicorp.com/vault/api-docs/auth/approle]\n',
  'APPROLE-008':
    'version: 1\nrule:\n  id: APPROLE-008\n  status: stable\n  enabled: true\n  severity: critical\n  finding_kind: security_issue\n  title: Privileged AppRole with weak credentials\n  description: A privileged role combines high-impact policies with weak SecretID controls.\n  remediation: Require SecretID, expiration and bounded reuse; consider CIDR binding.\n  object_types: [approle]\n  detector: approle_compound\n  parameters:\n    weak_fields: [bind_secret_id, secret_id_num_uses, secret_id_ttl]\n    severity_mapping: {secret_id_disabled: critical, unlimited_and_non_expiring: high}\n  documentation: [https://developer.hashicorp.com/vault/api-docs/auth/approle]\n',
  'JWT-001':
    'version: 1\nrule:\n  id: JWT-001\n  status: review\n  enabled: true\n  severity: critical\n  finding_kind: security_issue\n  title: Privileged policy assigned to JWT/OIDC role\n  description: The role issues a policy classified as privileged.\n  remediation: Use a dedicated tightly-bound role and least-privilege policy.\n  object_types: [jwt_role]\n  detector: jwt_privileged_policy\n  parameters:\n    severity_mapping: {root: critical, administrative: high}\n  documentation: [https://developer.hashicorp.com/vault/api-docs/auth/jwt]\n',
  'JWT-002':
    'version: 1\nrule:\n  id: JWT-002\n  status: review\n  enabled: true\n  severity: medium\n  finding_kind: review_recommendation\n  title: JWT audience not constrained\n  description: A JWT role has no configured bound audience; applicability depends on issuer token shape.\n  remediation: Require the expected audience where JWTs carry an aud claim.\n  object_types: [jwt_role]\n  detector: jwt_audience\n  parameters:\n    applies_to_role_type: jwt\n    field: bound_audiences\n  documentation: [https://developer.hashicorp.com/vault/api-docs/auth/jwt]\n',
  'JWT-003':
    'version: 1\nrule:\n  id: JWT-003\n  status: review\n  enabled: true\n  severity: info\n  finding_kind: review_recommendation\n  title: JWT role has no additional bound claims\n  description: The role lacks organization-specific claim restrictions required by audit configuration.\n  remediation: Define required claims for sensitive mounts in audit configuration.\n  object_types: [jwt_role]\n  detector: jwt_bound_claims\n  parameters:\n    fields: [bound_claims, bound_subject]\n  documentation: [https://developer.hashicorp.com/vault/api-docs/auth/jwt]\n',
  'JWT-005':
    'version: 1\nrule:\n  id: JWT-005\n  status: review\n  enabled: true\n  severity: medium\n  finding_kind: risky_configuration\n  title: Long-lived JWT/OIDC Vault token\n  description: The generated Vault token TTL exceeds a configured threshold.\n  remediation: Reduce token_ttl/token_max_ttl or document the requirement.\n  object_types: [jwt_role]\n  detector: jwt_token_ttl\n  parameters:\n    fields: [token_ttl, token_max_ttl]\n  documentation: [https://developer.hashicorp.com/vault/api-docs/auth/jwt]\n',
  'JWT-006':
    'version: 1\nrule:\n  id: JWT-006\n  status: stable\n  enabled: true\n  severity: medium\n  finding_kind: risky_configuration\n  title: Overly broad JWT bound-claim glob\n  description: A configured claim glob admits a broad identity population.\n  remediation: Replace broad globs with exact values or narrow prefixes.\n  object_types: [jwt_role]\n  detector: jwt_broad_glob\n  parameters:\n    claim_type: glob\n    severity_mapping: {regular: medium, privileged: high}\n  documentation: [https://developer.hashicorp.com/vault/api-docs/auth/jwt]\n',
  'K8S-001':
    'version: 1\nrule:\n  id: K8S-001\n  status: review\n  enabled: true\n  severity: medium\n  finding_kind: risky_configuration\n  title: Wildcard Kubernetes service account name\n  description: All service account names can use this role within its namespace scope.\n  remediation: Bind the role to explicit service account names.\n  object_types: [kubernetes_role]\n  detector: kubernetes_wildcard_name\n  parameters:\n    field: bound_service_account_names\n    wildcard: "*"\n  documentation: [https://developer.hashicorp.com/vault/api-docs/auth/kubernetes]\n',
  'K8S-002':
    'version: 1\nrule:\n  id: K8S-002\n  status: review\n  enabled: true\n  severity: medium\n  finding_kind: risky_configuration\n  title: Wildcard Kubernetes namespace\n  description: Service accounts from every namespace can use this role within its name scope.\n  remediation: Bind the role to explicit namespaces or a reviewed selector.\n  object_types: [kubernetes_role]\n  detector: kubernetes_wildcard_namespace\n  parameters:\n    field: bound_service_account_namespaces\n    wildcard: "*"\n  documentation: [https://developer.hashicorp.com/vault/api-docs/auth/kubernetes]\n',
  'K8S-003':
    'version: 1\nrule:\n  id: K8S-003\n  status: stable\n  enabled: true\n  severity: high\n  finding_kind: risky_configuration\n  title: Unbounded Kubernetes workload identity\n  description: Both service account name and namespace are wildcarded.\n  remediation: Use explicit service account names and namespaces.\n  object_types: [kubernetes_role]\n  detector: kubernetes_double_wildcard\n  parameters:\n    fields: [bound_service_account_names, bound_service_account_namespaces]\n    wildcard: "*"\n  documentation: [https://developer.hashicorp.com/vault/api-docs/auth/kubernetes]\n',
  'K8S-004':
    'version: 1\nrule:\n  id: K8S-004\n  status: stable\n  enabled: true\n  severity: critical\n  finding_kind: security_issue\n  title: Privileged policy on wildcard Kubernetes role\n  description: A broad Kubernetes identity population receives a privileged policy.\n  remediation: Remove wildcard bindings and issue a least-privilege policy.\n  object_types: [kubernetes_role]\n  detector: kubernetes_privileged_wildcard\n  parameters:\n    severity_mapping: {single_wildcard: high, double_wildcard: critical}\n  documentation: [https://developer.hashicorp.com/vault/api-docs/auth/kubernetes]\n',
  'K8S-005':
    'version: 1\nrule:\n  id: K8S-005\n  status: review\n  enabled: true\n  severity: medium\n  finding_kind: risky_configuration\n  title: Long-lived Kubernetes Vault token\n  description: The generated Vault token TTL exceeds a configured threshold.\n  remediation: Reduce token_ttl/token_max_ttl or document the requirement.\n  object_types: [kubernetes_role]\n  detector: kubernetes_token_ttl\n  parameters:\n    fields: [token_ttl, token_max_ttl]\n  documentation: [https://developer.hashicorp.com/vault/api-docs/auth/kubernetes]\n',
  'K8S-006':
    'version: 1\nrule:\n  id: K8S-006\n  status: review\n  enabled: true\n  severity: info\n  finding_kind: review_recommendation\n  title: Kubernetes role restriction requires review\n  description: The role has no clearly recognized namespace restriction.\n  remediation: Configure explicit namespaces or a reviewed namespace selector.\n  object_types: [kubernetes_role]\n  detector: kubernetes_restriction_review\n  parameters:\n    fields: [bound_service_account_namespaces, bound_service_account_namespace_selector]\n  documentation: [https://developer.hashicorp.com/vault/api-docs/auth/kubernetes]\n',
  'POL-001':
    'version: 1\nrule:\n  id: POL-001\n  status: stable\n  enabled: true\n  severity: critical\n  finding_kind: security_issue\n  title: Global Vault API wildcard\n  description: A root wildcard grants broad access to current and future Vault API paths.\n  remediation: Replace it with explicit minimum endpoints.\n  object_types: [acl_policy]\n  detector: root_wildcard\n  parameters:\n    root_paths: ["*", "+"]\n    mutating_capabilities: [create, update, delete, patch]\n  documentation: [https://developer.hashicorp.com/vault/docs/concepts/policies]\n',
  'POL-002':
    'version: 1\nrule:\n  id: POL-002\n  status: stable\n  enabled: true\n  severity: high\n  finding_kind: risky_configuration\n  title: Dangerous sudo capability\n  description: Sudo enables root-protected operations when combined with the required operation capability.\n  remediation: Remove sudo or restrict it to an exact reviewed root-protected endpoint.\n  object_types: [acl_policy]\n  detector: sudo_capability\n  parameters:\n    root_protected_prefixes: [sys/auth, sys/policies, sys/policy, sys/mounts, sys/audit, auth/token, sys/replication, sys/raw, sys/rotate, sys/seal]\n  documentation: [https://developer.hashicorp.com/vault/docs/concepts/policies]\n',
  'POL-003':
    'version: 1\nrule:\n  id: POL-003\n  status: stable\n  enabled: true\n  severity: critical\n  finding_kind: security_issue\n  title: ACL policy administration\n  description: The policy can create, change or delete authorization policy definitions.\n  remediation: Move ACL administration to a separate break-glass policy.\n  object_types: [acl_policy]\n  detector: acl_policy_administration\n  parameters:\n    prefixes: [sys/policy, sys/policies/acl]\n    protected_names: [root, default, vault-admins]\n    severity_mapping: {broad_or_self: critical, scoped: high}\n  documentation: [https://developer.hashicorp.com/vault/docs/concepts/policies]\n',
  'POL-004':
    'version: 1\nrule:\n  id: POL-004\n  status: stable\n  enabled: true\n  severity: critical\n  finding_kind: security_issue\n  title: Auth method administration\n  description: The policy can create, reconfigure or remove authentication methods.\n  remediation: Restrict management to an exact reviewed auth mount.\n  object_types: [acl_policy]\n  detector: auth_mount_administration\n  parameters:\n    prefix: sys/auth\n    severity_mapping: {broad: critical, scoped: high}\n  documentation: [https://developer.hashicorp.com/vault/docs/concepts/policies]\n',
  'POL-005':
    'version: 1\nrule:\n  id: POL-005\n  status: stable\n  enabled: true\n  severity: high\n  finding_kind: risky_configuration\n  title: Token issuance capability\n  description: The policy can create child, orphan or token-role credentials, or alter token roles.\n  remediation: Remove issuance access or constrain the exact token role and its policy set.\n  object_types: [acl_policy]\n  detector: token_issuance\n  parameters:\n    paths: [auth/token/create, auth/token/create-orphan, auth/token/create/*, auth/token/roles/*]\n    severity_mapping: {child: medium, orphan: high, token_role_issuance: high, token_role_administration: high}\n  documentation: [https://developer.hashicorp.com/vault/api-docs/auth/token]\n',
  'POL-006':
    'version: 1\nrule:\n  id: POL-006\n  status: review\n  enabled: true\n  severity: high\n  finding_kind: risky_configuration\n  title: Broad secrets-engine access\n  description: The policy grants access across an entire secrets-engine data or metadata namespace.\n  remediation: Replace the mount-wide wildcard with the smallest application-owned prefix.\n  object_types: [acl_policy]\n  detector: broad_secret_path\n  parameters:\n    broad_relative_paths: ["*", "+", "data/*", "metadata/*"]\n    excluded_mount_types: [cubbyhole]\n    capability_severity: {mutating: high, read: high, list: medium}\n  documentation: [https://developer.hashicorp.com/vault/docs/concepts/policies]\n',
  'POL-007':
    'version: 1\nrule:\n  id: POL-007\n  status: review\n  enabled: true\n  severity: high\n  finding_kind: risky_configuration\n  title: Shallow Vault API wildcard\n  description: A wildcard close to the Vault API root can cover unrelated current and future endpoints.\n  remediation: Move the wildcard below a reviewed subsystem or replace it with exact paths.\n  object_types: [acl_policy]\n  detector: contextual_wildcard\n  parameters:\n    wildcard_tokens: ["*", "+"]\n    maximum_static_prefix_segments: 1\n    capability_severity: {mutating: high, read_or_list: medium}\n    exclude_root_wildcard: true\n    exclude_discovered_secret_mounts: true\n  documentation: [https://developer.hashicorp.com/vault/docs/concepts/policies]\n',
  'POL-008':
    'version: 1\nrule:\n  id: POL-008\n  status: review\n  enabled: true\n  severity: high\n  finding_kind: security_issue\n  title: Audit device administration\n  description: The policy can enable, modify or disable Vault audit devices and affect security visibility.\n  remediation: Keep audit-device administration in a narrowly assigned operational policy.\n  object_types: [acl_policy]\n  detector: audit_device_administration\n  parameters:\n    paths: [sys/audit, "sys/audit/*"]\n    excluded_paths: [sys/audit-hash, "sys/audit-hash/*"]\n    operations: [create, update, delete, patch]\n  documentation: [https://developer.hashicorp.com/vault/api-docs/system/audit]\n',
  'POL-009':
    'version: 1\nrule:\n  id: POL-009\n  status: review\n  enabled: true\n  severity: critical\n  finding_kind: security_issue\n  title: Secrets-engine mount administration\n  description: The policy can mount, reconfigure or remove secrets engines.\n  remediation: Restrict mount administration to exact reviewed mount paths and break-glass identities.\n  object_types: [acl_policy]\n  detector: mount_administration\n  parameters:\n    paths: [sys/mounts, "sys/mounts/*"]\n    severity_mapping: {broad: critical, scoped: high}\n  documentation: [https://developer.hashicorp.com/vault/api-docs/system/mounts]\n',
  'POL-010':
    'version: 1\nrule:\n  id: POL-010\n  status: review\n  enabled: true\n  severity: critical\n  finding_kind: security_issue\n  title: Self-service auth role escalation\n  description: A role receives a policy that can modify the same role before re-authentication.\n  remediation: Remove role mutation from policies issued by that role and separate administration.\n  object_types: [approle, jwt_role, kubernetes_role, auth_role]\n  detector: escalation_graph\n  parameters:\n    require_observed_assignment: true\n    operations: [create, update, delete, patch]\n  documentation: [https://developer.hashicorp.com/vault/docs/concepts/policies]\n',
  'REF-001':
    'version: 1\nrule:\n  id: REF-001\n  status: stable\n  enabled: true\n  severity: medium\n  finding_kind: risky_configuration\n  title: Auth role references an absent ACL policy\n  description: An auth role names a policy that is not present in the collected Vault ACL policy catalog.\n  remediation: Remove the stale policy name from the role or create and review the intended least-privilege policy.\n  object_types: [approle, jwt_role, kubernetes_role]\n  detector: missing_policy_reference\n  documentation:\n    - https://developer.hashicorp.com/vault/docs/concepts/policies\n',
  'POL-011':
    'version: 1\nrule:\n  id: POL-011\n  status: review\n  enabled: true\n  severity: critical\n  finding_kind: security_issue\n  title: Assigned policy can modify itself\n  description: An observed auth role assignment grants mutation of the same ACL policy definition, allowing expansion followed by re-authentication.\n  remediation: Separate ACL policy administration from identities that receive the administered policy.\n  object_types: [approle, jwt_role, kubernetes_role, auth_role]\n  detector: self_policy_escalation\n  parameters: {}\n  documentation: [https://developer.hashicorp.com/vault/docs/concepts/policies]\n',
  'POL-012':
    'version: 1\nrule:\n  id: POL-012\n  status: experimental\n  enabled: true\n  severity: high\n  finding_kind: security_issue\n  title: Token-role administration and issuance chain\n  description: The same observed role assignment permits modification of a token role and token creation through that role.\n  remediation: Separate token-role administration from token issuance and narrowly scope both paths.\n  object_types: [approle, jwt_role, kubernetes_role, auth_role]\n  detector: token_role_escalation\n  parameters: {}\n  documentation: [https://developer.hashicorp.com/vault/api-docs/auth/token]\n',
  'POL-013':
    'version: 1\nrule:\n  id: POL-013\n  status: review\n  enabled: true\n  severity: high\n  finding_kind: review_recommendation\n  title: Mutation of another privileged auth role\n  description: An assigned policy can change another auth role that issues privileged policies, but access to authenticate through the target role is not proven.\n  remediation: Separate role administration and verify that source principals cannot satisfy the target role identity constraints.\n  object_types: [approle, jwt_role, kubernetes_role, auth_role]\n  detector: privileged_role_mutation\n  parameters: {}\n  documentation: [https://developer.hashicorp.com/vault/docs/concepts/policies]\n',
  'POL-014':
    'version: 1\nrule:\n  id: POL-014\n  status: experimental\n  enabled: true\n  severity: high\n  finding_kind: risky_configuration\n  title: Auth-mount bootstrap capability chain\n  description: An observed role assignment combines auth mount administration with broad auth method configuration capabilities.\n  remediation: Separate sys/auth administration from auth method configuration and remove broad auth path mutation.\n  object_types: [approle, jwt_role, kubernetes_role, auth_role]\n  detector: auth_mount_bootstrap\n  parameters: {}\n  documentation: [https://developer.hashicorp.com/vault/api-docs/system/auth]\n',
  'POL-015':
    "version: 1\nrule:\n  id: POL-015\n  status: review\n  enabled: true\n  severity: critical\n  finding_kind: security_issue\n  title: ACL creation and self-role assignment chain\n  description: An observed role assignment permits both ACL policy creation and mutation of that role's own policy assignments.\n  remediation: Separate ACL policy administration from auth role administration and require independent operators for both actions.\n  object_types: [approle, jwt_role, kubernetes_role, auth_role]\n  detector: policy_role_assignment_chain\n  parameters: {}\n  documentation: [https://developer.hashicorp.com/vault/docs/concepts/policies]\n",
};
